version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql-messagerie
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messagerie
      MYSQL_USER: nabil
      MYSQL_PASSWORD: nabil123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: spring-backend
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/messagerie
      SPRING_DATASOURCE_USERNAME: nabil
      SPRING_DATASOURCE_PASSWORD: nabil123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data: