spring.application.name=backend
server.port=8080

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# JWT
jwt.secret=messagerie-secure-chat-jwt-secret-key-2024-minimum-32-characters-required
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# DATABASE (LOCAL)
spring.datasource.url=jdbc:mysql://localhost:3306/messagerie?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect